# Generated by Django 4.2.4 on 2023-08-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0002_excercise_user_userlog_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
