# Generated by Django 4.2.4 on 2023-08-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='correct_answers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='excercise_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='total_questions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
