# Generated by Django 4.2.4 on 2023-08-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0005_alter_userlog_correct_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='excercise_id',
            new_name='exercise_id',
        ),
    ]
