# Generated by Django 4.2.4 on 2023-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0006_rename_excercise_id_userlog_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date_completed',
            field=models.CharField(max_length=100),
        ),
    ]
